### ISSUE TITLE
automatic TestSet and xTest creation

### ISSUE THREAD

**Issue by radzimir** [telekom/testerra-xray-connector#5]
Please add optional functionality for automatic creation of "Test Set" and "xTest" issues in Jira.
For every test class annotated with @XrayTestSet a "Test Set" should be created if missing.
For every test method annotated with @Test a "xTest" should be created if missing, then added to corresponding “Test Set”. If xTest was found, should be only added to “Test Set”.
After test run, every xTest in "Test Set" that wasn't updated (wasn't seen in @XrayTestSet) should be removed from "Test Set". If test isn’t used anymore, it should be tagged as obsolete - such tests could be removed manually some day when Jira allows that functionality.

Automatic removal of "Test Set" should not be implemented.

**Comment by mreiche** [comment]
Final requirements:
- XRay connector should be able to create Test sets or tests based on classes and methods.
- Synchronization should be done by class context name or method context name.
- This feature should be optional enabled via property
- Using ticket IDs is not mandatory anymore, but should be primary used


Risks:
- What happens when a test / test set was renamed in Jira or Testerra? They will be recreated as long no ID link is present.

Postponed requirements:
- Automatic synchronisation and removal of tests from test sets is to dangerous
